name: Deploy Backend
on:
  push:
    paths: ["backend/**"]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and Push
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/limmagenie_backend:latest ./backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/limmagenie_backend:latest
